# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'trigger'
  #    - '**.sh'
  #    - '**.yml'
  schedule:
            - cron:  "0 7 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    # Runs a single command using the runners shell
    - name: Proccessing Hosts...
      run: bash ./Download-and-Process-Hosts.sh
    - name: Upload Backups to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output/backup/*
        tag: v1.0.0-backup
        overwrite: true
        file_glob: true
        body: "These files get automatically updated every 24 hours."
    - name: Upload Hosts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output/main/*
        tag: v1.0.0
        overwrite: true
        file_glob: true
        body: "These files get automatically updated every 24 hours."
    - name: Cleanup
      run: rm -f -r output/

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto Update
        branch: master
        commit_options: '--no-verify --signoff'
        repository: .
        commit_user_name: j-moriarti
        commit_user_email: j-moriarti@users.noreply.github.com
        push_options: '--force'
